name: tests
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
    dependencies:
      name: Dependencies
      runs-on: ubuntu-20.04

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup golang
          uses: actions/setup-go@v3
          with:
            go-version: 1.18

    unit-tests:
      name: Unit Tests
      needs: dependencies
      runs-on: ubuntu-20.04

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          
        - name: Running Unit Tests
          run: make test